language: php
php:
    - '5.6'
before_install:
    - php /home/travis/.phpenv/versions/5.6/bin/composer self-update
install:
    - composer install
before_script:
    # starting demo server
    - sudo apt-get update
    - sudo apt-get install apache2 libapache2-mod-fastcgi
script:
    - vendor/bin/phpunit
